# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20171026_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='tripOrginizer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
